CVweb/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^jet/', include('jet.urls', 'jet')),
    url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('product/', include('product.urls')),
    path('blog/', include('blog.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/urls.py
from django.conf.urls import url
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
app_name = "blog"

urlpatterns = [
    path('', views.index, name = 'index'),
    path('search', views.search),
    path('<topic>/<slug>/', views.post, name = 'post'),
    
    path('register/', views.register, name="register"),
    path('login/',auth_views.LoginView.as_view(template_name="login.html"), name="login"),
    path('logout/',auth_views.LogoutView.as_view(next_page='/blog'),name='logout'),
    path('<topicname>/', views.topicview, name = 'topic'),
]

blog/models.py
from django.db import models
from django.conf import settings
from django.utils.text import slugify
from six import python_2_unicode_compatible
from ckeditor_uploader.fields import RichTextUploadingField
from ckeditor.fields import RichTextField
# Create your models here.
class topic(models.Model):
    name = models.CharField(max_length=255, primary_key=True)
    showname = models.CharField(max_length=255, null= True)

    def __str__(self):
        return self.name

class article(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique= True, blank=True, editable=True, null = True)
    topic = models.ForeignKey(topic, on_delete=models.CASCADE)
    author = models.CharField(max_length=255)
    opening = models.TextField()
    body = RichTextUploadingField()
    date = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(null = True)
    view = models.IntegerField(default=0, null=True)
    

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(article, self).save(*args, **kwargs)
    

class Comment(models.Model):
    post = models.ForeignKey(article, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)



    

blog/forms.py
from django import forms
import re
from django.contrib.auth.models import User
from .models import Comment

class RegistrationForm(forms.Form):
    username = forms.CharField(label='Tài khoản', max_length=30)
    email = forms.EmailField(label='Email')
    password1 = forms.CharField(label='Mật khẩu', widget=forms.PasswordInput())
    password2 = forms.CharField(label='Nhập lại mật khẩu', widget=forms.PasswordInput())

    def clean_password2(self):
        if 'password1' in self.cleaned_data:
            password1 = self.cleaned_data['password1']
            password2 = self.cleaned_data['password2']
            if password1 == password2 and password1:
                return password2
        raise forms.ValidationError("Mật khẩu không hợp lệ")

    def clean_username(self):
        username = self.cleaned_data['username']
        if not re.search(r'^', username):
            raise forms.ValidationError("Tên tài khoản có kí tự đặc biệt")
        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username
        raise forms.ValidationError("Tài khoản đã tồn tại")

    def save(self):
        User.objects.create_user(username=self.cleaned_data['username'], email=self.cleaned_data['email'], password=self.cleaned_data['password1'])

class CommentForm(forms.ModelForm):
    
    def __init__(self, *args, **kwargs):
        self.author = kwargs.pop('author', None)
        self.post = kwargs.pop('post', None)
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        comment = super().save(commit=False)
        comment.author = self.author
        comment.post = self.post
        comment.save()

    class Meta:
        model = Comment
        fields = ["body"]

class Search(forms.Form):
    keyword = forms.CharField( max_length=200, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Search',}))

blog/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from .models import article, topic, Comment
from django.http import Http404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import RegistrationForm, CommentForm, Search
# Create your views here.
def index(request):
    Data = { 'Book' : article.objects.filter(topic = 'book').order_by('-date')[:6],
    'Code': article.objects.filter(topic = 'code').order_by('-date')[:6],
    'Travel': article.objects.filter(topic = 'travel').order_by('-date')[:6],
    'Others': article.objects.filter(topic = 'others').order_by('-date')[:6],
    'newest' : article.objects.all().order_by('-date')[:5],
    'most': article.objects.all().order_by('-view')[:5],
    'new4' : article.objects.all().order_by('-date')[:4],
    }
    return render(request, 'index.html', Data)

def search(request, *args):
    if request.GET:
        keyword = request.GET['keyword']
        liststr = keyword.split(" ")
        result = article.objects.all()
        for i in liststr:
            result = result.filter(body__icontains=i).order_by('-date')
        form = Search
        newest = article.objects.all().order_by('-date')[:5]
        most = article.objects.all().order_by('-view')[:5]
        return render(request, 'search.html', {'form':form, 'result': result, 'newest': newest, 'most': most })
    form = Search
    newest = article.objects.all().order_by('-date')[:5]
    most = article.objects.all().order_by('-view')[:5]
    return render(request, 'search.html', {'form':form,'newest': newest, 'most': most })

def post(request, topic, slug):
    try:
        post = article.objects.get(slug = slug)
    except article.DoesNotExist:
        raise Http404("Bài viết không tồn tại")
    blog_post_slug = slug
    if not blog_post_slug in request.session:
        post.view += 1
        post.save()
        # Insert the slug into the session as the user has seen it
        request.session[blog_post_slug] = blog_post_slug
    articleList = article.objects.filter(topic = topic).order_by('-date')[:5]
    form = CommentForm()
    if request.method == "POST":
        form = CommentForm(request.POST, author=request.user, post=post)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(request.path)
    newest = article.objects.all().order_by('-date')[:5]
    most = article.objects.all().order_by('-view')[:5]
    return render(request, 'article.html', {'article': post, 'form' : form, 'articleList': articleList,'newest': newest, 'most': most })

def topicview(request, topicname):
    try:
        topic1 = topic.objects.get(name = topicname)
    except topic.DoesNotExist:
        raise Http404("Chủ đề không tồn tại")
    Article = article.objects.filter(topic = topicname).order_by('-date')
    paginator = Paginator(Article, 3)
    pageNumber = request.GET.get('page')
    
    try:
        Article = paginator.page(pageNumber)
    except PageNotAnInteger:
        Article = paginator.page(1)
    except EmptyPage:
        Article = paginator.page(paginator.num_pages)
    newest = article.objects.all().order_by('-date')[:5]
    most = article.objects.all().order_by('-view')[:5]
    return render(request, 'topic.html', {'Article': Article, 'topic': topic1, 'newest': newest, 'most': most} )

def register(request):
    form = RegistrationForm()
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/blog')
    return render(request, 'register.html', {'form': form})

blog/templates/article.html
{% extends "base.html" %}
{% load static %}
{% block title %} {{ article.title }} {% endblock %}
{% block meta %}
    <meta property="og:image" content="{{ article.image.url }}">
    <meta property="og:title" content="{{ article.title }}">
    <meta property="og:description" content="{{ article.opening }}">
{% endblock %}
{% block content %}
<div class="row" style="margin: auto; ">
<div class="col-xl-0"></div>
<div class="col-xl-12" style="margin: auto">
    <br>
    <a href="./" style="color: #0066CC;"><h3>{{article.title}}</h3></a>
    <br>
    
    <h6><small><font size=2><i><img style="height: 1em;" src="{% static 'clock.png' %}"> {{ article.date|date:"d-m-Y" }}</i></font></small></h6>
    <p style="text-align: right; color:#0066CC; margin-top: -2em"> <img style="height: 1em;" src="{% static 'view.png' %}"> {{ article.view }}</p>
    
    <br>
    
    <img src="{{ article.image.url }}" style="width: 100%; ">
    
    <br>
    <br>
    <p style="text-align: justify; width: 100%;"> {{article.body|safe}} </p>
    <p style="margin-top: 5%"><h5><strong><label>Bình luận:</label></strong></h5></p>
    {% for comment in article.comments.all %}
        <div class="media border p-3">
            <div class="media-body">
                <h4><strong>{{comment.author}}</strong> &nbsp; <small><font size=2.5><i>{{comment.date}}</i></font></small></h4>        
                <p>{{comment.body|safe|linebreaks}}</p>
            </div>
        </div>
    {% endfor %}
    {% if user.username %}
        <form action="{% url 'blog:post' article.topic article.slug %}" method="POST" >
            {% csrf_token %}
            <p><strong><label>Viết bình luận:</label></strong></p>
            <div style="max-width: 70%">{{form.body}}</div>
            <br/>
            <input type="submit" value="Bình luận" >
        </form>
    {% endif %}
    <p style="margin-top: 5%"><h5><strong><label>Bài viết liên quan:</label></strong></h5></p>
    {% for post in articleList %}
        
        <a href="{% url 'blog:post' post.topic post.slug %}" target="_blank"> <h6 style="color:#0066CC ;"> {{ post.title }} </h6></a>
    {% endfor %}
</div>
</div>
        
    
{% endblock %}

blog/templates/index.html
{% extends "base.html" %}

{% block title %} Long Phan - Myblog {% endblock %}
{% block meta %}
    <meta property="og:url" content="http://longphanspace.pythonanywhere.com/blog" />
    <meta property="og:image" content="http://longphanspace.pythonanywhere.com/static/longphan.jpg" />
    <meta property="og:title" content="Long Phan - My Blog" />
    <meta property="og:description" content="Blog chia sẻ cá nhân" />
{% endblock %}
{% block css %}
<style>
@media screen and (max-width: 576px) {
    div.menubar {
        width: 40%;
    }
    #anh1 {
        padding: 0px;
        padding-right: 0;
    }
}
@media screen and (min-width: 577px) {
    #anh1 {
        padding: 0px;
        padding-right: 5px;
    }
}
</style>
{% endblock %}

{% block content %}
    <div class="row" style="padding: 10px; margin-top: 10px">
        {% for post in new4 %}
            {% if forloop.first %}
            <div id="anh1" class="row col-md-6" style="margin: 0; margin-top: 5px;  ">
                <a href="{% url 'blog:post' post.topic post.slug %}" target="_blank"><img src="{{ post.image.url }}" style="width: 100%; height: 400px;object-fit: cover"></a>
                <p style="margin-top: -3em; background-color: rgba(0, 0, 0, 0.247); text-align: justify; margin-bottom: 0; min-width: 100%; min-height: 3em;">
                    <a href="{% url 'blog:topic' post.topic %}" target="_blank" style="font-size: 0.7em; background-color: #0066cc; color: white; padding: 2px 5px; border-radius: 5px; width: fit-content;"> {{post.topic.showname}}</a>
                    <a href="{% url 'blog:post' post.topic post.slug %}" target="_blank" style=" color: white; font-weight: bold; padding: 0 5px;">{{post.title}}</a>
                </p>
            </div>
            {% elif forloop.counter == 2 %}

            <div class="row col-md-6" style="margin: 0; margin-top: 5px; padding: 0px; ">
                <a href="{% url 'blog:post' post.topic post.slug %}" target="_blank"><img src="{{ post.image.url }}" style="width:100%; height: 200px;object-fit: cover"></a>
                <p style="margin-top: -3em; background-color: rgba(0, 0, 0, 0.247); margin-bottom: 0; text-align: justify; min-width: 100%; min-height: 3em;">
                <a href="{% url 'blog:topic' post.topic %}" target="_blank" style="font-size: 0.7em; background-color: #0066cc; color: white; padding: 2px 5px; border-radius: 5px; width: fit-content;"> {{post.topic.showname}}</a>
                <a href="{% url 'blog:post' post.topic post.slug %}" target="_blank" style=" color: white; font-weight: bold; padding: 0 5px;">{{post.title}}</a>
                </p>
            {% elif forloop.counter == 3 %}

            <div class="col-6 row" style="margin: 0; padding: 0px; padding-right: 5px; padding-top: 5px; ">
                <a href="{% url 'blog:post' post.topic post.slug %}" target="_blank"><img src="{{ post.image.url }}" style="width:100%; height: 195px;object-fit: cover"></a>
                <p style="bottom: 0; margin-top: -4.5em; background-color: rgba(0, 0, 0, 0.247); text-align: justify; min-width: 100%; min-height: 3em;">
                    <a href="{% url 'blog:topic' post.topic %}" target="_blank" style="font-size: 0.7em; background-color: #0066cc; color: white; padding: 2px 5px; border-radius: 5px; width: fit-content;"> {{post.topic.showname}}</a>
                    <a href="{% url 'blog:post' post.topic post.slug %}" target="_blank" style=" color: white; font-weight: bold; padding: 0 5px;">{{post.title}}</a>
                </p>
            </div>
            {% elif forloop.counter == 4 %}
            <div class="col-6 row" style="margin: 0; padding: 0px; padding-top: 5px; ">
                <a href="{% url 'blog:post' post.topic post.slug %}" target="_blank"><img src="{{ post.image.url }}" style="width:100%; height: 195px;object-fit: cover"></a>
                <p style="margin-top: -4.5em; background-color: rgba(0, 0, 0, 0.247); text-align: justify; min-width: 100%; min-height: 3em;">
                    <a href="{% url 'blog:topic' post.topic %}" target="_blank" style="font-size: 0.7em; background-color: #0066cc; color: white; padding: 2px 5px; border-radius: 5px; width: fit-content;"> {{post.topic.showname}}</a>
                    <a href="{% url 'blog:post' post.topic post.slug %}" target="_blank" style=" color: white; font-weight: bold; padding: 0 5px;">{{post.title}}</a>
                    </p>
            </div>
            </div>

            {% endif %}
        {% endfor %}
    </div>
    <div class="row" >
        <div class="col-md-6" style="margin-top: 5%">
            <div class="menubar col-md-6" style="background-color:#0066CC; text-align: center; height: 2em; width: 35%; border-top-right-radius: 100px ;">

                <a href="{% url 'blog:topic' 'book' %}" style="color:white; vertical-align: middle;"> SÁCH</a>
            </div>
            <div style="background-color:#0066CC; height: 2px; margin-top: -2px"></div>
            <div class="row" style="margin-top: 20px; ">
                {% for book in Book %}
                    {% if forloop.first %}
                    <div class="col-md-6" >
                            <a href="{% url 'blog:post' book.topic book.slug %}" target="_blank"><img src="{{ book.image.url }}" style="width: 100%; height: 150px; object-fit: cover"></a>
                            <a href="{% url 'blog:post' book.topic book.slug %}" target="_blank"> <h5 style="color:#0066CC; text-align:justify"> {{ book.title }} </h5></a>
                            <p style="text-align:justify;">{{ book.opening|truncatewords:40 }}</p>
                    </div>
                    <div class="col-md-6">
                        {% else %}
                                <div class="row">
                                <div class="col-4" style="margin:auto; margin:0; padding: 0">
                                    <a href="{% url 'blog:post' book.topic book.slug %}" target="_blank"><img style="width: 100%; height: 70px; object-fit: cover" src="{{ book.image.url }}" ></a>
                                </div>
                                <div class="col-8" style="margin:auto">
                                    <a href="{% url 'blog:post' book.topic book.slug %}" style="color:#0066CC; text-align:justify; " target="_blank">  {{ book.title }} </a><br>
                                </div>
                                </div>
                                <br>
                        {% endif %}

                    {% endfor %}
                    </div>
            </div>
        </div>
        <div class="col-md-6" style="margin-top: 5%">
            <div style="background-color:#0066CC; text-align: center; height: 2em; width: 35%; border-top-right-radius: 100px ;">
                <a href="{% url 'blog:topic' 'code' %}" style="color:white; vertical-align: middle;"> LẬP TRÌNH</a>
            </div>
            <div style="background-color:#0066CC; height: 2px; margin-top: -2px"></div>
            <div class="row" style="margin-top: 20px">
                {% for code in Code %}
                    {% if forloop.first %}
                    <div class="col-md-6">
                            <a href="{% url 'blog:post' code.topic code.slug %}" target="_blank"><img src="{{ code.image.url }}" style="width: 100%;height: 150px; object-fit: cover"></a>
                            <a href="{% url 'blog:post' code.topic code.slug %}" target="_blank"> <h5 style="color:#0066CC; text-align:justify"> {{ code.title }} </h5></a>
                            <p style="text-align:justify;">{{ code.opening|truncatewords:40 }}</p>
                    </div>
                    <div class="col-md-6">
                            {% else %}
                                    <div class="row">
                                    <div class="col-4" style="margin:auto; margin:0; padding: 0">
                                        <a href="{% url 'blog:post' code.topic code.slug %}" target="_blank"><img style="width: 100%;height: 70px; object-fit: cover " src="{{ code.image.url }}"></a>
                                    </div>
                                    <div class="col-8" style="margin:auto">
                                        <a href="{% url 'blog:post' code.topic code.slug %}" style="color:#0066CC; text-align:justify" target="_blank">  {{ code.title }} </a><br>
                                    </div>
                                    </div>
                                    <br>
                            {% endif %}

                        {% endfor %}
                    </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6" style="margin-top: 5%">
            <div style="background-color:#0066CC; text-align: center; height: 2em; width: 35%; border-top-right-radius: 100px ;">
                <a href="{% url 'blog:topic' 'travel' %}" style="color:white; vertical-align: middle;"> DU LỊCH</a>
            </div>
            <div style="background-color:#0066CC; height: 2px; margin-top: -2px"></div>

            <div class="row" style="margin-top: 20px">
                {% for travel in Travel %}
                    {% if forloop.first %}
                    <div class="col-md-6">
                            <a href="{% url 'blog:post' travel.topic travel.slug %}" target="_blank"><img src="{{ travel.image.url }}" style="width: 100%;height: 150px; object-fit: cover"></a>
                            <a href="{% url 'blog:post' travel.topic travel.slug %}" target="_blank"> <h5 style="color:#0066CC; text-align:justify"> {{ travel.title }} </h5></a>
                            <p style="text-align:justify;">{{ travel.opening|truncatewords:40 }}</p>
                    </div>
                    <div class="col-md-6">
                        {% else %}
                                <div class="row" >
                                <div class="col-4" style="margin:auto; margin:0; padding: 0">
                                    <a href="{% url 'blog:post' travel.topic travel.slug %}" target="_blank"><img style="width: 100%; height: 70px; object-fit: cover" src="{{ travel.image.url }}"></a>
                                </div>
                                <div class="col-8" style="margin:auto">
                                    <a href="{% url 'blog:post' travel.topic travel.slug %}" style="color:#0066CC; text-align:justify" target="_blank">  {{ travel.title }} </a><br>
                                </div>
                                </div>
                                <br>
                        {% endif %}

                        {% endfor %}
                    </div>
            </div>
        </div>
        <div class="col-md-6" style="margin-top: 5%">
            <div style="background-color:#0066CC; text-align: center; height: 2em; width: 35%; border-top-right-radius: 100px ;">
                <a href="{% url 'blog:topic' 'others' %}" style="color:white; vertical-align: middle;">LINH TINH</a>
            </div>
            <div style="background-color:#0066CC; height: 2px; margin-top: -2px"></div>
            <div class="row" style="margin-top: 20px">
                {% for other in Others %}
                    {% if forloop.first %}
                    <div class="col-md-6">
                            <a href="{% url 'blog:post' other.topic other.slug %}" target="_blank"><img src="{{ other.image.url }}" style="width: 100%;height: 150px; object-fit: cover"></a>
                            <a href="{% url 'blog:post' other.topic other.slug %}" target="_blank"> <h5 style="color:#0066CC; text-align:justify"> {{ other.title }} </h5></a>
                            <p style="text-align:justify;">{{ other.opening|truncatewords:40 }}</p>
                        </div>
                        <div class="col-md-6">
                            {% else %}
                                    <div class="row" >
                                    <div class="col-4" style="margin:auto; margin:0; padding: 0">
                                        <a href="{% url 'blog:post' other.topic other.slug %}" target="_blank"><img style="width: 100%; height: 70px; object-fit: cover" src="{{ other.image.url }}"></a>
                                    </div>
                                    <div class="col-8" style="margin:auto">
                                        <a href="{% url 'blog:post' other.topic other.slug %}" style="color:#0066CC; text-align:justify" target="_blank">  {{ other.title }} </a><br>
                                    </div>
                                    </div>
                                    <br>
                            {% endif %}

                        {% endfor %}
                        </div>
            </div>
        </div>
    </div>

{% endblock %}

blog/templates/login.html
{% extends "base.html" %}

{% block title %} Đăng nhập {% endblock %}

{% block content %}

<div class="col-md-12" style="text-align: center; margin-top: 5%; color: #0066CC">
    <form method="POST">
        {% csrf_token %}
        {% for key, value in form.errors.items %}
            {{value}}
        {% endfor %}
        <p><label>Tài khoản:</label>{{form.username}}</p>
        <p><label>Mật khẩu:</label>{{form.password}}</p>
        <input type="hidden" name="next" value="/blog"/>
        <input type="submit" value="Đăng nhập" style="color: white; background-color: #0066CC; border: 0; border-radius: 50px; padding: 3px 10px"/>
    </form>
</div>

{% endblock %}

blog/templates/register.html
{% extends "base.html" %}

{% block title %} Đăng ký tài khoản {% endblock %}

{% block content %}

<div style="margin:auto; margin-top: 5%; color: #0066CC">
    <form action="." method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Đăng ký" style="margin:auto; color: white; background-color: #0066CC; border: 0; border-radius: 50px; padding: 3px 10px"/>
    </form>
</div>

{% endblock %}

blog/templates/search.html
{% extends "base.html" %}

{% block title %} Search {% endblock %}



{% block content %}

<div class="row" style="margin:auto; margin-top: 20px;">
    
    <form style="margin:auto;" class="form-inline" action="" method="GET" class="form-horizontal">
       
        <table>
            {{ form.as_table }}
        </table>
        <input style="border-radius: 50px; background-color: #0066CC; color: white; border: 0; margin-left: 10px;" type="submit" value="Search" />
        
    </form>
    
</div>

<div style="margin:auto; margin-top: 20px;" >
    
    {% for post in result %}
    <div class="row">
    <div class="col-4" style="margin:auto; padding: 0;">   
        <a href="{% url 'blog:post' post.topic post.slug %}" target="_blank"><img src="{{ post.image.url }}" style="width: 100%;"></a>
    </div>
    <div class="col-8" style="margin:auto">   
        <a href="{% url 'blog:post' post.topic post.slug %}" style="color:#0066CC; text-align:justify" target="_blank">  {{ post.title }} </a>
        <p style="text-align:justify">{{ post.opening|truncatewords:40 }} </p>
    </div>
    </div><br>
    {% endfor %}
    
</div>
{% endblock %}

blog/templates/topic.html
{% extends "base.html" %}

{% block title %} {{ topic.showname }} {% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-0"></div>
    <div class="col-md-12">
    {% for article in Article %}
        <br>               
        <a href="{% url 'blog:topic' article.topic %}{{article.slug }}" target="_blank"><img src="{{ article.image.url }}" style="width: 100%;"></a>
        <a href="{% url 'blog:topic' article.topic %}{{article.slug }}" target="_blank"> <h4 style="color:#0066CC ;"> {{ article.title }} </h4></a>
        <p style="text-align:justify">{{ article.opening }}</p>
        <div style="background-color:#0066CC; height: 2px; width: 25%; margin-left: 50%; transform: translate(-50%)" ></div>
    {% empty %}
        <br>
        <h5 style="text-align: center;"><i>Nội dung này chưa có bài viết...</i></h5>
    {% endfor %}
    <br>
    {% if Article %}
        <div class="pagination" style="margin-left: 50%; transform: translate(-50%); text-align: center; padding-left: 10%; position: relative;">
            <div class="step-links" style=" margin-left: -20%; transform: translate(-50%); position: absolute;">
                {% if Article.has_previous %}
                    <a style="background-color:#0066CC ; border-top-left-radius: 50px; border-bottom-left-radius: 50px; padding: 2px 7px; color: white" href="?page={{ Article.previous_page_number }}">Trang trước</a>
                {% endif %}
            </div>
        
            <div class="current" style=" margin-left: 30%; transform: translate(-50%); position: absolute;">
                Trang {{ Article.number }} / {{ Article.paginator.num_pages }}
            </div>
            
            <div  style=" margin-left: 80%; transform: translate(-50%); position: absolute; width: 100%; ">
                {% if Article.has_next %}
                    <a style="background-color:#0066CC ; border-top-right-radius: 50px; border-bottom-right-radius: 50px; padding: 2px 10px; color: white" href="?page={{ Article.next_page_number }}">Trang sau</a>
                {% endif %}
            </div>
        </div>
    {% endif %}
    <br>
</div>
</div>
    
{% endblock %}